import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Protein Shake",
    category: "Protein",
    price: 6.99,
    image: "/placeholder-product.png",
    isSelfServeEnabled: true,
    inventoryCount: 24,
  },
  {
    id: "2",
    name: "Chicken Caesar Wrap",
    category: "Grab & Go",
    price: 9.99,
    image: "/placeholder-product.png",
    isSelfServeEnabled: true,
    inventoryCount: 12,
  },
  {
    id: "3",
    name: "Hot Turkey Panini",
    category: "Hot Food",
    price: 10.99,
    image: "/placeholder-product.png",
    isHotFood: true,
    isSelfServeEnabled: false,
    inventoryCount: 8,
  },
  {
    id: "4",
    name: "Gatorade",
    category: "Drinks",
    price: 3.25,
    image: "/placeholder-product.png",
    isSelfServeEnabled: true,
    inventoryCount: 40,
  },
  {
    id: "5",
    name: "Granola Bar",
    category: "Snacks",
    price: 2.49,
    image: "/placeholder-product.png",
    isSelfServeEnabled: true,
    inventoryCount: 50,
  },
  {
    id: "6",
    name: "Liberty T-Shirt",
    category: "Merch",
    price: 22.0,
    image: "/placeholder-product.png",
    isSelfServeEnabled: true,
    inventoryCount: 10,
  },
];